### PR TITLE
Make compatible with iOS Extensions again

### PR DESCRIPTION
**Pull request by lexrus**
see also #54  
Help merge @andyyc 's branch with master since he hasn't responded for a while and this feature is very important for my project.

### CODE REVIEW

**Comment by djih** [comment]
@lexrus so @andyyc mentioned some metrics were incorrect due to unexpected background/foreground behavior with extensions. Are you having those issues?

**Comment by andyyc** [comment]
Thanks for taking this over @lexrus.

@djih, I don't know for sure that the metrics are incorrect, I haven't tested extensively enough to know definitively.  But from what I understand, there's a delay when events are logged.  So you can imagine a scenario where the user opens our keyboard, performs some actions that are logged, then closes our keyboard all under 30s.  (I'm not sure how long iOS let's our app run in the background for extensions or if it's suspended immediately).  In this case, since enterBackground is never called, the events may never get uploaded until the next time the keyboard or app is opened.

It's not a huge issue for me and I've been running Amplitude with my diff for a couple months now without any major problems.

Thanks!

**Comment by andyyc** [comment]
okay I just tried this.  It looks like the app is suspended immediately after closing the keyboard, so the event isn't getting uploaded until the next time the keyboard is opened.  I could probably alleviate this by decreasing the eventUploadPeriodSeconds value.

**Comment by djih** [comment]
Closing this as https://github.com/amplitude/Amplitude-iOS/pull/99 will be going out in the next release

**Pull request closed without merging**
