### PR TITLE
feat: Add support for watchOS

### LINKED ISSUE #247: watchOS support
Sorry to bring this up again, but how can this not be on your roadmap? If you have a standalone Watch app, this is a must have and for us it would be the reason to switch to a competitor able to track our users on the Watch. 

With standalone watch apps it is not possible to take the route via iPhone app anymore and watchOS also introduced subscriptions, which makes it important to track events as you will be able to generate revenue by optimizing stuff.

### PR DESCRIPTION
**Pull request by daltonclaybrook**
### Summary

Resolves #247 

This PR updates the SDK to include support for watchOS. The only consequential change to the SDK is the addition of a new type: `AMPBackgroundNotifier`. The doc comment in that file explains its purpose:

>watchOS adds support for background notifications in watchOS 7.0 with `WKExtension.applicationDidEnterBackgroundNotification` and related notifications. But since this SDK is backward-compatible with watchOS 3.0, these notifications are not available. Instead, the user should implement the appropriate background methods on their Extension Delegate and call the `AMPBackgroundNotifier` from those methods.

I've also updated the Podspec to add watchOS support. Feel free to make changes to this branch as you see fit.

### Checklist

* [x] Does your PR title have the correct [title format](https://github.com/amplitude/Amplitude-iOS/blob/main/CONTRIBUTING.md#pr-commit-title-conventions)?
* Does your PR have a breaking change?:  No

### CODE REVIEW

**Comment by haoliu-amp** [comment]
@daltonclaybrook Thanks! This is great. We will review it soon.

**Comment by haoliu-amp** [comment]
@daltonclaybrook LGTM. Have you tried `logEvent` in your watchOS app? Any issues with that?

**Review by haoliu-amp — APPROVED** [review]
@daltonclaybrook LGTM. Have you tried logEvent in your watchOS app? Any issues with that?

**Comment by daltonclaybrook** [comment]
@haoliu-amp I'm planning to do some testing on this today and will let you know.

**Comment by daltonclaybrook** [comment]
@haoliu-amp I did some basic testing yesterday on-device and was seeing events in the dashboard. Not a comprehensive test, but anecdotally, it seems to be working.

**Comment by haoliu-amp** [comment]
@daltonclaybrook Thank you spending time to do the testing! We will release it very soon!

**Pull request merged**
