### PR TITLE
Swift package support

### PR DESCRIPTION
**Pull request by mayur1407**
Need Amplitude to be integrated as the Swift package. Requesting all the contributor's assistance in this pull request.

### CODE REVIEW

**Comment by benjohnde** [comment]
Would also love to see this merged soon :)

**Comment by haoliu-amp** [comment]
Thanks for your PR, @mayur1407 ! Can you explain why you created the `Source` directory?

**Comment by mayur1407** [comment]
Hi @haoliu-amp , SwiftPM has its own pre-defined structure. Hence, had to create the source folder. The package.swift consider the **source** folder only for the source code at its root level.

**Comment by haoliu-amp** [comment]
Got it, and would you like to update `Amplitude-iOS.podspec` file too? This file needs to be changed, otherwise importing it from pods will fail. 

For Ln 11 and 12,
`  s.source_files           = 'Sources/Amplitude/*.{h,m}', 'Sources/Amplitude/SSLCertificatePinning/*.{h,m}'
  s.resources              = 'Sources/Amplitude/*.der'`

Thanks again.

**Comment by mayur1407** [comment]
Sure, updated the `Amplitude-iOS.podspec` file. Please check

**Comment by haoliu-amp** [comment]
@mayur1407 Thanks for that. One last thing is my question in you adding `@import Foundation;` to  `AMPIdentify.h` file. What is that for?

**Comment by mayur1407** [comment]
Thanks @haoliu-amp to identify this. While converting to package, the Swift package manager was unable to find the Foundation framework. So, intentionally importing it in any class making it work. It seems strange to me that it is not reproducible in my latest Xcode version. Hence, reversed this commit.

**Comment by haoliu-amp** [comment]
@mayur1407 Thanks for you contribution! Merged!

**Comment by mayur1407** [comment]
Thanks, @haoliu-amp for your assistance. Happy to contribute.

**Comment by schjonhaug** [comment]
I'm facing some issues when adding it to my project:

Skjermbilde 2019-11-21 kl  09 44 16

Skjermbilde 2019-11-21 kl  09 44 42

**Comment by mayur1407** [comment]
Hi @schjonhaug , I think I don't have access to create the tag for this. Please select the second option **Branch** in the Rules section and type **master** in the branch name. This approach allows you in sync with the latest commit in the branch.

Thanks

@haoliu-amp : I tried tagging this commit and it's not reflecting in this repository. Can you please provide the tag for this commit So that we can integrate Amplitude with a specified version also. Thanks

**Comment by haoliu-amp** [comment]
Guys, we've release a new version 4.9.0 including Swift Package Manager support.

Please check - 
https://github.com/amplitude/Amplitude-iOS/releases
https://cocoapods.org/pods/Amplitude-iOS

Cheers!

**Comment by mayur1407** [comment]
@schjonhaug : I have provided this fix. You can check the PR #216 status. Thanks for identifying and prompt updates. I am also waiting for this pull request approval. 
If we don't get further tag update after this merge we can mention the branch name "master" in the rule section and can continue.

**Comment by haoliu-amp** [comment]
I have released a new version 4.9.3. Pls use that. That has addressed the errors to use Swift Package Manager.

**Pull request merged**
