### PR TITLE
Added framework target for Carthage compatibility

### PR DESCRIPTION
**Pull request by mpurland**

### CODE REVIEW

**Comment by josh-fuggle** [comment]
Any update on this? Can it be merged in?

**Comment by djih** [comment]
@mpurland thanks for the PR! @josh-fuggle  We will take a look sometime next week sorry for the delay

**Comment by lexrus** [comment]
@djih Any update?

**Comment by djih** [comment]
@lexrus sorry for the delay, should have this released by EOW

**Comment by djih** [comment]
I've pulled the branch, updated with master, and built successfully with Carthage: https://github.com/amplitude/Amplitude-iOS/compare/mpurland-framework. Now I need to verify that I can load it into a demo app using Carthage

**Comment by djih** [comment]
@mpurland @lexrus @josh-fuggle are you guys able to integrate Amplitude via Carthage if you add
`github "amplitude/Amplitude-iOS" "mpurland-framework"` to your Cartfile?

**Comment by loudnate** [comment]
Works fine, though these errors do appear:

screen shot 2016-06-21 at 6 35 36 pm

**Comment by djih** [comment]
@loudnate thanks for the info. I just added those ISP headers to the framework. Can you `carthage update` and see if those warning messages are still there? Thanks

**Comment by loudnate** [comment]
Sorry for the slow response – that fixes the warning messages for me.

**Comment by lexrus** [comment]
Could you clean the warnings and publish it to master branch?

```
*** Cloning Amplitude-iOS
*** Checking out Amplitude-iOS at "a3d6720626e72a678489bce83ed9dacadb505dd7"
*** xcodebuild output can be found in /var/folders/_n/p_0zqmfx2qd5vz2pq7n82gfc0000gn/T/carthage-xcodebuild.6CbHzS.log
*** Building scheme "AmplitudeFramework" in Amplitude.xcworkspace
/Users/lex/git/Trackable/Carthage/Checkouts/Amplitude-iOS/Amplitude/AMPRevenue.m:78:21: warning: expression result unused [-Wunused-value]
/Users/lex/git/Trackable/Carthage/Checkouts/Amplitude-iOS/Amplitude/AMPRevenue.m:92:21: warning: expression result unused [-Wunused-value]
/Users/lex/git/Trackable/Carthage/Checkouts/Amplitude-iOS/Amplitude/AMPRevenue.m:100:21: warning: expression result unused [-Wunused-value]
/Users/lex/git/Trackable/Carthage/Checkouts/Amplitude-iOS/Amplitude/AMPRevenue.m:108:21: warning: expression result unused [-Wunused-value]
/Users/lex/git/Trackable/Carthage/Checkouts/Amplitude-iOS/Amplitude/Amplitude.m:464:25: warning: expression result unused [-Wunused-value]
/Users/lex/git/Trackable/Carthage/Checkouts/Amplitude-iOS/Amplitude/Amplitude.m:1284:25: warning: expression result unused [-Wunused-value]
/Users/lex/git/Trackable/Carthage/Checkouts/Amplitude-iOS/Amplitude/Amplitude.m:1326:25: warning: expression result unused [-Wunused-value]
/Users/lex/git/Trackable/Carthage/Checkouts/Amplitude-iOS/Amplitude/AMPDatabaseHelper.m:135:35: warning: expression result unused [-Wunused-value]
/Users/lex/git/Trackable/Carthage/Checkouts/Amplitude-iOS/Amplitude/AMPRevenue.m:78:21: warning: expression result unused [-Wunused-value]
/Users/lex/git/Trackable/Carthage/Checkouts/Amplitude-iOS/Amplitude/AMPRevenue.m:92:21: warning: expression result unused [-Wunused-value]
/Users/lex/git/Trackable/Carthage/Checkouts/Amplitude-iOS/Amplitude/AMPRevenue.m:100:21: warning: expression result unused [-Wunused-value]
/Users/lex/git/Trackable/Carthage/Checkouts/Amplitude-iOS/Amplitude/AMPRevenue.m:108:21: warning: expression result unused [-Wunused-value]
/Users/lex/git/Trackable/Carthage/Checkouts/Amplitude-iOS/Amplitude/Amplitude.m:464:25: warning: expression result unused [-Wunused-value]
/Users/lex/git/Trackable/Carthage/Checkouts/Amplitude-iOS/Amplitude/Amplitude.m:1284:25: warning: expression result unused [-Wunused-value]
/Users/lex/git/Trackable/Carthage/Checkouts/Amplitude-iOS/Amplitude/Amplitude.m:1326:25: warning: expression result unused [-Wunused-value]
/Users/lex/git/Trackable/Carthage/Checkouts/Amplitude-iOS/Amplitude/AMPDatabaseHelper.m:135:35: warning: expression result unused [-Wunused-value]
/Users/lex/git/Trackable/Carthage/Checkouts/Amplitude-iOS/Amplitude/AMPRevenue.m:78:21: warning: expression result unused [-Wunused-value]
/Users/lex/git/Trackable/Carthage/Checkouts/Amplitude-iOS/Amplitude/AMPRevenue.m:92:21: warning: expression result unused [-Wunused-value]
/Users/lex/git/Trackable/Carthage/Checkouts/Amplitude-iOS/Amplitude/AMPRevenue.m:100:21: warning: expression result unused [-Wunused-value]
/Users/lex/git/Trackable/Carthage/Checkouts/Amplitude-iOS/Amplitude/AMPRevenue.m:108:21: warning: expression result unused [-Wunused-value]
/Users/lex/git/Trackable/Carthage/Checkouts/Amplitude-iOS/Amplitude/Amplitude.m:464:25: warning: expression result unused [-Wunused-value]
/Users/lex/git/Trackable/Carthage/Checkouts/Amplitude-iOS/Amplitude/Amplitude.m:1284:25: warning: expression result unused [-Wunused-value]
/Users/lex/git/Trackable/Carthage/Checkouts/Amplitude-iOS/Amplitude/Amplitude.m:1326:25: warning: expression result unused [-Wunused-value]
/Users/lex/git/Trackable/Carthage/Checkouts/Amplitude-iOS/Amplitude/AMPDatabaseHelper.m:135:35: warning: expression result unused [-Wunused-value]
/Users/lex/git/Trackable/Carthage/Checkouts/Amplitude-iOS/Amplitude/AMPRevenue.m:78:21: warning: expression result unused [-Wunused-value]
/Users/lex/git/Trackable/Carthage/Checkouts/Amplitude-iOS/Amplitude/AMPRevenue.m:92:21: warning: expression result unused [-Wunused-value]
/Users/lex/git/Trackable/Carthage/Checkouts/Amplitude-iOS/Amplitude/AMPRevenue.m:100:21: warning: expression result unused [-Wunused-value]
/Users/lex/git/Trackable/Carthage/Checkouts/Amplitude-iOS/Amplitude/AMPRevenue.m:108:21: warning: expression result unused [-Wunused-value]
/Users/lex/git/Trackable/Carthage/Checkouts/Amplitude-iOS/Amplitude/Amplitude.m:464:25: warning: expression result unused [-Wunused-value]
/Users/lex/git/Trackable/Carthage/Checkouts/Amplitude-iOS/Amplitude/Amplitude.m:1284:25: warning: expression result unused [-Wunused-value]
/Users/lex/git/Trackable/Carthage/Checkouts/Amplitude-iOS/Amplitude/Amplitude.m:1326:25: warning: expression result unused [-Wunused-value]
/Users/lex/git/Trackable/Carthage/Checkouts/Amplitude-iOS/Amplitude/AMPDatabaseHelper.m:135:35: warning: expression result unused [-Wunused-value]
```

**Comment by lexrus** [comment]
AmplitudeFramework.framework is kinda weird.
Could you rename the product name to Amplitude.framework ?

**Comment by mpurland** [comment]
I'd be glad to change it. What's the name of the CocoaPods framework? It should be Amplitude.framework, right?

**Comment by djih** [comment]
@mpurland yea that would be great. Would there be any conflicts since the existing codebase is already named Amplitude?

**Comment by djih** [comment]
@lexrus I have cleaned up the warnings in the `mpurland-framework` branch

**Comment by lexrus** [comment]
@djih Warnings are gone. Thank you so much.

**Comment by djih** [comment]
@mpurland anything I can do to help with renaming the framework? I tried renaming the Schema but I think there's a namespace conflict with the Amplitude source.

**Comment by djih** [comment]
@lexrus I don't actually think it's possible to rename the framework to `Amplitude.framework`. It conflicts with the `Amplitude` scheme, which is our static library. @mpurland I'm just going to merge it as is. People integrating through Carthage will have to import headers with `#import "AmplitudeFramework/Amplitude.h". The extra `AmplitudeFramework` is a little awkward but it should be fine.

**Pull request merged**
