### PR TITLE
Amplitude SSL Pinning included with Amplitude's Cocoapod

### PR DESCRIPTION
**Pull request by aaronwasserman**
Per my correspondence with Varun, Wendy and Dan, we're hoping to enable SSL Pinning in our implementation of Amplitude. The instructions Dan gave us was to:

a. download the source from https://github.com/amplitude/Amplitude-iOS/archive/master.zip
b. install the entire 'Amplitude' subdirectory directly into our project

From my examination of your pod spec, it would appear the only reason ☝️ is necessary is because the pod spec _only_ includes .h / .m files in the top level folder. 

This PR simply modifies the pod spec to include everything in the 'Amplitude' folder, so that (hopefully) we're not forced to choose between integrating Amplitude via Cocoapods or enabling SSL Pinning.

### CODE REVIEW

**Comment by djih** [comment]
@aaronwasserman are you able to get the SSL pinning working via Cocoapods with this? I'm going to test it out myself as well

**Comment by aaronwasserman** [comment]
@djih Not yet, unfortunately. When I add the preprocessor macro:
` AMPLITUDE_SSL_PINNING=1 `
I get a compiler failure in 
`Amplitude+SSLPinning.h`
`Error:(12, 12) cannot find interface declaration for 'Amplitude'`

I'm speaking with Dan (@ amplitude) about this... 

I've confirmed that in my forked branch (with the podspec set to include everything in the Amplitude folder) the files are identical (and all are included).  So I'm not exactly sure why the compiler failure (yet).

**Comment by djih** [comment]
@aaronwasserman (I'm Dan btw).

I just copied your branch and installed it into our demo app. Here's our Podfile:

```platform :ios, '7.0'

target 'm2048' do
    pod 'Amplitude-iOS', :git => 'https://github.com/Amplitude/Amplitude-iOS.git', :branch => 'ssl_pinning_cocoapods'
end

post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'AMPLITUDE_SSL_PINNING=1']
        end
    end
end
```

And that seems to be working. It looks like you have to specify the preprocessor macros via the Podfile, doesn't seem to work if you add it directly to your build settings. I did get 2 compile errors around needing to add `(__bridge CFTypeRef)`, but after that it was working.

**Comment by aaronwasserman** [comment]
Hah dunno why I didn't realize it was you Dan! 👋 

Just added those two compiler errors you mentioned to my PR (in case that's helpful), and will confirm this is now working (after I've added the preprocessor macro instructions to my Podfile post install script).

**Comment by aaronwasserman** [comment]
@djih Everything now compiles from my forked branch, and I can confirm `AMPLITUDE_SSL_PINNING` is now enabled.

The response I get back from the `AMPURLConnection` API call is 
`Error Domain=NSURLErrorDomain Code=-1012 "(null)" UserInfo={NSErrorFailingURLKey=https://api.amplitude.com/, NSErrorFailingURLStringKey=https://api.amplitude.com/}
`

I believe -1012 is NSURLErrorUserCancelledAuthentication , so something could still be wrong with SSL Pinning?

**Comment by djih** [comment]
@aaronwasserman ok I'm seeing it to:

```
2017-01-31 14:06:04.816 m2048[24091:286942] Failed to load a certificate
2017-01-31 14:06:09.155 m2048[24091:286945] Error accessing the SSL Pins plist at ~/Library/SSLPins.plist
2017-01-31 14:06:11.135 m2048[24091:286607] ERROR: Connection error:Error Domain=NSURLErrorDomain Code=-1012 "(null)" UserInfo={NSErrorFailingURLKey=https://api.amplitude.com/, NSErrorFailingURLStringKey=https://api.amplitude.com/}
2017-01-31 14:06:11.211 m2048[24091:286941] Error accessing the SSL Pins plist at ~/Library/SSLPins.plist
```

I think the Cocoapods installation messed up the directory paths and it's not able to load the certificate in the directory. I'm digging into it

**Comment by aaronwasserman** [comment]
Ok thanks for the update. If there’s anything else you’d like me to try or change in this PR, happy to help.

**Comment by djih** [comment]
@aaronwasserman so I've narrowed it down to Cocoapods and resource bundles. The AMPURLConnection fails to find the certificate file because it's no longer in the bundle: https://github.com/amplitude/Amplitude-iOS/blob/master/Amplitude/AMPURLConnection.m#L40

I've experimented modifying the podspec file, adding:
`s.resource_bundles       = { "Amplitude" => ['Amplitude/*.der']}`
but not able to get Xcode to find it.

**Comment by djih** [comment]
If I print out the bundle resolved path `/Users/danieljih/Library/Developer/CoreSimulator/Devices/0B88AF47-7011-4155-B446-B0C98644EA0F/data/Containers/Bundle/Application/DD7611DF-2B21-4F36-A0CB-AA8A11A2FC67/m2048.app`, and then go there and show the package contents of m2048.app, I do see `Amplitude.bundle`. If I show package contents of Amplitude.bundle, I see all the cert files. So basically I need to update the certPath to find those files.

**Comment by aaronwasserman** [comment]
While this certainly isn't what I was expecting, when comparing the "Compile Sources" build phase of your source downloaded directly from git, none of the .der files are included. Yet when I look at the same build phase in my Amplitude target managed by Cocoapods, they _are_. I wonder if that's somehow affecting the pathForResource lookup?

**Comment by djih** [comment]
@aaronwasserman I think I figured it out. Need to add `s.resources = "Amplitude/*.der"` to the podspec (ignore the resource_bundles that I mentioned earlier). It's able to find the cert files now. Although I don't think you can test it properly in a simulator since I get this error:

```
2017-01-31 15:16:06.987 m2048[29000:333081] Failed to register: Error Domain=NSCocoaErrorDomain Code=3010 "remote notifications are not supported in the simulator" UserInfo={NSLocalizedDescription=remote notifications are not supported in the simulator}
```

**Comment by aaronwasserman** [comment]
Ok want me to do that in this PR?

**Comment by djih** [comment]
@aaronwasserman yes please. Also you should test to see if that fixes your issues and allows for events to be sent.

**Comment by aaronwasserman** [comment]
@djih I committed the required changes to my forked repo, so this PR is now up to date. I assumed that if you guys were going to merge it in, you'd want to control the pod spec version number so you'll note I've left that unchanged.

I'm running the changes in my simulator, and now back to getting 400s in the response to
```
- (void)makeEventUploadPostRequest:(NSString*) url events:(NSString*) events numEvents:(long) numEvents maxEventId:(long long) maxEventId maxIdentifyId:(long long) maxIdentifyId
```

In your message above you noted the 3010 error for simulator. Was this just in the response to registering for remote notifications? If so, everyone gets that when they run sim builds because simulator devices can't receive push notifications. Do you think that's related?

**Comment by aaronwasserman** [comment]
Disregard ☝️ .... The 400s were because of a different issue on my machine.  I can now confirm I'm getting 200s back from the upload call, so I think we're all good!  Thanks so much for your help and let me know if there's anything else needed to close out the PR.

**Comment by djih** [comment]
@aaronwasserman yes that is correct, I mentioned it might not work properly in simulator. I'm glad we were able to get it working. I will do a little more testing myself, and release this as a new version either tonight or tomorrow. Thanks for your help!

**Comment by aaronwasserman** [comment]
Great! Thanks to you as well.

**Comment by djih** [comment]
@aaronwasserman tested it on our test device, looks good. Merged and released as v3.14.0: https://github.com/amplitude/Amplitude-iOS/releases/tag/v3.14.0

**Comment by aaronwasserman** [comment]
Thanks Dan! I’ve deleted our forked repo, and redirected our Cocoapod install to your master branch for 3.14.

Best,
Aaron

**Pull request merged**
