### PR TITLE
add the ability to set the device ID

### PR DESCRIPTION
**Pull request by tsheaff**
This was a response to a thread Xin and @coderholic and I had about setting the device ID.  This is important to our needs.  The javascript SDK allows setting the device ID.

If you want more context about our reasoning let me know and I'd be happy to provide.

### CODE REVIEW

**Comment by tsheaff** [comment]
Unclear why the tests failed.  When I ran the tests locally *before* making these changes I got the same error:

`Terminating app due to uncaught exception 'NSGenericException', reason: '*** Collection <__NSArrayM: 0x7fd7f1875f10> was mutated while being enumerated.'`

**Comment by tsheaff** [comment]
@djih can we get this looked at.  Reasonably simple change that's important for our needs.

**Comment by djih** [comment]
@tsheaff yep working on it now. I'm adding some tests to make sure it works

**Comment by tsheaff** [comment]
Sweet.  Thanks!

**Comment by djih** [comment]
https://github.com/amplitude/Amplitude-iOS/commit/bfe56869bbb034321b1c909dad70ff97b02c3009 will be in the next release

**Comment by djih** [comment]
@tsheaff : also make sure you see our comments regarding setDeviceId: https://github.com/amplitude/Amplitude-iOS#advanced

**Comment by djih** [comment]
@tsheaff : this is also done for our android sdk: https://github.com/amplitude/Amplitude-Android/commit/90bbdc87fc5b3bab71d9b754b81e582b4dda712b

**Comment by tsheaff** [comment]
@djih fantastic.  Thanks a bunch!

**Comment by djih** [comment]
@tsheaff: this is released with v3.2.0: https://github.com/amplitude/Amplitude-iOS/releases/tag/v3.2.0 please update your pod file

This is also released with v2.2.0 for Android: https://github.com/amplitude/Amplitude-Android/releases/tag/v2.2.0, although it might take another hour or two to show up in Maven central

**Comment by tsheaff** [comment]
:+1:

**Pull request closed without merging**
