### PR TITLE
Swift package support: Fixed foundation error

### PR DESCRIPTION
**Pull request by mayur1407**
Have to import foundation framework as some classes are importing it directly or indirectly.

### CODE REVIEW

**Comment by haoliu-amp** [comment]
Hey @mayur1407 , before merging this, I saw there're other classes doesn't import foundation framework too. Can you help test if those classes work? 

Reasons are:
1. I wonder if those classes broke too. If yes, then they need to add the foundation framework too.
2. I wonder if it's specific to Swift Package Manager.

**Comment by mayur1407** [comment]
Hi @haoliu-amp , I have been using this and It has not given any error so far. I suspect this caused due to package env.  I have also observed some classes are not importing Foundation and working fine though(no compiler error). I will investigate it further. Meanwhile, I request you to provide this patch release.

**Comment by mayur1407** [comment]
@haoliu-amp : Also, I wanted to check If I can share the demo application or doc update to integrate the Amplitude package in the project.

**Comment by haoliu-amp** [comment]
@mayur1407  I actually tested it with your change, but still getting errors. I also need to look into it what'll be the best practice for Swift Package Manager. Pls let me know if you have new finds.

Screen Shot 2019-11-22 at 2 25 03 PM

**Comment by haoliu-amp** [comment]
Close this since it's been fixed, but thank you again.

**Comment by mayur1407** [comment]
Thanks, @haoliu-amp

**Pull request closed without merging**
