### PR TITLE
add OSX support

### PR DESCRIPTION
**Pull request by philippb**
This pull request adds OS X support to the amplitude iOS lib.

We're running this in production with https://itunes.apple.com/us/app/keep-safe-private-photo-vault/id1078477965?ls=1&mt=12

The only open question is, who to define sessions on the desktop. It's not as obvious as on mobile because of multi task.

CC @curtisliu PR based on our email conversation.

### CODE REVIEW

**Comment by djih** [comment]
Hi @philippb, thanks for the PR. I will take a look next week, although we might need to do some more testing on our end before we incorporate it.

**Comment by djih** [comment]
@philippb : for the vendor id it looks like you guys are trying to fetch the MAC Address of the device instead. Is that a use case for you guys? AFAIK the vendor id information actually doesn't get used or shown on our Dashboards. Even if they were unavailable on OSX devices that should be okay.

**Comment by philippb** [comment]
@djih sorry just saw this. Looking at the diff, we're just putting a compiler `#if` around the iOS specific stuff.

**Comment by djih** [comment]
@philippb  no problem. are you guys trying to use the Mac address as the device Id?

**Pull request closed without merging**
