### PR TITLE
Add macOS support

### LINKED ISSUE #138: Is macOS expected to be supported?
It has been a long time since this library was released and there is still no support for macOS. For companies that support versions of applications for iOS and macOS, this imposes certain difficulties in the support of several analytic systems. Are there any plans to eliminate this shortcoming?

### PR DESCRIPTION
**Pull request by rob-keepsafe**
Closes #138 

### Changes

- Adds macOS support to the common frameworks
- Adds macOS test target with all targets passing 
- Ensures tests continue passing on iOS and tvOS targets
- Uses an abstract target on the Podfile to share pods/versions

**Note:** Seems there are some pre-existing race conditions when running all tests at once, but rest assured all tests on all targets ran and passed individually (and occasionally when run all at once).

### TODO (post-merge)

Tasks for the repo maintainers:

- Update podspec
- Update README

### Used in

We have used this and will continue to use this in production at [Keepsafe](https://github.com/KeepSafe).

### CODE REVIEW

**Comment by asam139** [comment]
Could someone review it to be accepted?

**Comment by desunit** [comment]
@djih any plans to merge this pull request?

**Comment by djih** [comment]
cc @blazzy  let's dicuss

**Comment by desunit** [comment]
@djih any updates?

**Comment by nikitakirichek** [comment]
@djih Any updates regarding this PR?

**Comment by haoliu-amp** [comment]
@nikitakirichek We might add macOS support soon. Before that we need to fully test it.

**Comment by rob-keepsafe** [comment]
Superseded by https://github.com/amplitude/Amplitude-iOS/pull/225

**Comment by nikitakirichek** [comment]
@haoliu-amp Great news! Thanks for mentioning.

**Pull request closed without merging**
