### PR TITLE
Fixing database path

### PR DESCRIPTION
**Pull request by gavrilaf**
We have to use 'stringByAppendingPathComponent' for database path. Current version doesn't work, because it can't open sqllite db.

### CODE REVIEW

**Comment by djih** [comment]
Thanks! We're working on releasing a patch ASAP

**Comment by djih** [comment]
We have rereleased v3.1.0 with the patch. You can get the latest version with pod install. You may need to clear your Cocoapods cache.

**Comment by gavrilaf** [comment]
Awesome! Thanks. Going  to your new version asap.

**Comment by djih** [comment]
Let us know if there are any more issues!

**Comment by gavrilaf** [comment]
Yep. Sure )

**Pull request closed without merging**
