### PR TITLE
Make compatible with iOS Extensions

### PR DESCRIPTION
**Pull request by andyyc**
I'm trying to use the sdk with a keyboard extension. Unfortunately, sharedApplication is unavailable in iOS extensions.

This diff replaces calls to sharedApplication with performSelector. This has been done in other places like SDWebImage here: rs/SDWebImage#1082 and doesn't appear to present any issues with App Store review.

### CODE REVIEW

**Comment by andyyc** [comment]
@djih any chance you could take a look at this?

**Comment by djih** [comment]
@andyyc I can take a look next week. Have you tested this with your extension?

**Comment by andyyc** [comment]
thanks @djih.  I've been using it in my app and haven't ran into any
issues, i.e. it runs fine without crashing and events are being logged.  I
am a little concerned, though, that some metrics are logged incorrectly due
to the fact that 'enterForeground' is never called.  I'm wondering if a
better solution would be simply to remove background uploading in the
extension entirely or switching to using NSURLSession to create a
background task as suggested here in "Performing Uploads and Downloads":
https://developer.apple.com/library/ios/documentation/General/Conceptual/ExtensibilityPG/ExtensionScenarios.html

**Comment by djih** [comment]
@andyyc so regarding the enterForeground, what kind of metrics are incorrect? All events logged will be in the "background" state, so if more than 5 minutes passes between logEvent calls, then it will start a new session. Maybe one temporary solution is just to increase the 5 min to something like 30 min.

Also it looks like in iOS 8.2 they added NSExtensionHostWillEnterForegroundNotification, which might be useful: http://stackoverflow.com/a/29988550, although our SDK currently has to support iOS 6.0. I wonder if it might be possible to still use those 8.2 methods if available.

Are there any issues with the background uploading? Do you need access to the app's data? Otherwise I don't think the NSURLSession and shared container is necessary.

Also, can you update from master (looks like there aren't any conflicts)? I fixed a bunch of flakey tests so your tests should pass now.

**Pull request closed without merging**
