### PR TITLE
Add AMPLITUDE_LOCATION_TRACKING preprocessor guard around location tracking code

### PR DESCRIPTION
**Pull request by jaltreuter**
Duplicate of #194 which was closed without merging with no comment on why.  Adding this code should allow users to silence the warnings from App Store Connect mentioned in #168.

cc members @blazzy who created #194 and @djih who commented on it.

### CODE REVIEW

**Comment by haoliu-amp** [comment]
@jaltreuter Thanks! Could you help resolve the conflicts? I can help merge once there's no conflicts. Sorry for not getting back to you in the past.

**Comment by jaltreuter** [comment]
I don't think I have the necessary permission to update that branch, so I'll have to put up another PR instead.  First though I'm trying to confirm the change actually works.

Also I've integrated Amplitude into my project via Cocoapods and found it tricky to add the necessary preprocessor flag in a way that would persist across runs of `pod install`.  The solution I found was to add this to my `Podfile`:

```
# Add a preprocessor macro to the generated Amplitude project that removes references to location tracking code
post_install do |installer|
  target = installer.pods_project.targets.find{|t| t.to_s == "Amplitude"}
  target.build_configurations.each do |config|
    s = config.build_settings['GCC_PREPROCESSOR_DEFINITIONS']
    s = [ '$(inherited)' ] if s == nil;
    s.push('AMPLITUDE_LOCATION_TRACKING=0')
    config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] = s
  end
end
```

This should probably be added to the README, but before I add that to this PR I'd be interested to know if someone who's more familiar with Cocoapods has a simpler solution.

**Comment by haoliu-amp** [comment]
@jaltreuter I will create a doc in our dev center since we keep all documentations there.
```
post_install do |installer_representation|
   installer_representation.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
         config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'AMPLITUDE_IDFA_TRACKING=1']
      end
   end
end
```

This is what I will recommend for it.

**Comment by jaltreuter** [comment]
@haoliu-amp thanks for cleaning that up.

Unfortunately when I forked this repo and created a branch with these changes (https://github.com/jaltreuter/Amplitude-iOS/tree/omit_location_code), and included the preprocessor flag as described above, Apple still produced a warning when I uploaded an archive of that code.

I removed this repo entirely from my codebase and uploaded an archive of that code, and Apple produced no warning.  So I'm confident that the issue somehow lies in this codebase, but I don't know where.

**Comment by haoliu-amp** [comment]
@jaltreuter What kind warnings are you seeing?

**Comment by jaltreuter** [comment]
> Dear Developer,
> 
> We identified one or more issues with a recent delivery for your app, "<my app name>" <app version>. Your delivery was successful, but you may wish to correct the following issues in your next delivery:
> 
> ITMS-90683: Missing Purpose String in Info.plist - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSLocationAlwaysUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting Spring 2019, all apps submitted to the App Store that access user data are required to include a purpose string. If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy).
> 
> ITMS-90683: Missing Purpose String in Info.plist - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSLocationWhenInUseUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting Spring 2019, all apps submitted to the App Store that access user data are required to include a purpose string. If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy).
> 
> After you’ve corrected the issues, you can upload a new binary to App Store Connect.
> 
> Best regards,
> 
> The App Store Team

**Comment by haoliu-amp** [comment]
@jaltreuter Have you confirmed that MARCO is in effect? Maybe put a break point to see if the location logic is getting called.

**Comment by jaltreuter** [comment]
@haoliu-amp I had some trouble confirming the macro is in effect, actually.  But the problem is bigger than that.  [I deleted the code entirely](https://github.com/jaltreuter/Amplitude-iOS/commit/85181b14b778767ad326a81ee5f3052c41d1eef0) and got the same warning from Apple.

**Comment by haoliu-amp** [comment]
@jaltreuter Is that the same warning? Or talking about other stuff but not location.

**Comment by jaltreuter** [comment]
@haoliu-amp the exact same warning.

**Comment by haoliu-amp** [comment]
@jaltreuter That's super odd. Those are pretty much the code for location tracking. Could you ask Apple to clarify? I wanna try it myself but we don't a mobile app.

**Comment by haoliu-amp** [comment]
@jaltreuter We make location tracking to be customer driven now. #281 
You can try with v7.0.0 now.

**Comment by jaltreuter** [comment]
@haoliu-amp thank you for continuing to look into this!  I'll update the library in my app to confirm it works as expected.

**Pull request closed without merging**
